-- Insert collections first (referenced by sequences)
INSERT INTO collections (name, description) VALUES 
('Human Genes', 'Important human genetic sequences for medical research'),
('Viral Genomes', 'Viral sequence data for pathogen research'),
('Bacterial Strains', 'Bacterial genetic sequences for microbiology studies'),
('Plant Genetics', 'Plant genetic sequences for agricultural research'),
('Human Proteins', 'Human protein sequences for structural biology'),
('RNA Molecules', 'Various RNA sequences for molecular biology');

-- Insert sequences with proper collection references
-- Human DNA sequences (collection_id: 1)
INSERT INTO sequences (collection_id, identifier, description, alphabet, sequence) VALUES 
(1, 'BRCA1_exon11', 'BRCA1 gene exon 11 fragment - breast cancer susceptibility', 'dna', 'ATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTAGGTCCGGTTATTGTAACAGACAAGTACCCCAAAGTGGCCAACAACAAGCAGGGATACAAAAATAAG'),
(1, 'TP53_exon5', 'TP53 tumor suppressor gene exon 5', 'dna', 'ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAG'),
(1, 'GAPDH_promoter', 'Glyceraldehyde-3-phosphate dehydrogenase promoter region', 'dna', 'CGCCCAATACGCAAACCGCCTCTCCCCGCGCGTTGGCCGATTCATTAATGCAGCTGGCACGACAGGTTTCCCGACTGGAAAGCGGGCAGTGAGCGCAACGCAATTAATGTGAGTTAGCTCACTCATTAGGCACCCCAGGCTTTACACTTTATGCTTCCGGCTCGTATGTTGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGAAACAGCTATGACCATGATTACGCC'),
(1, 'Human_mtDNA_COX1', 'Human mitochondrial cytochrome c oxidase I gene fragment', 'dna', 'ATGTTCGCCGACCGTTGACTATTCTCTACAAACCACAAAGACATTGGAACACTTTATTTTATTTTTGGTATTTGAGCAGGAATAATTGGAACATCACTAAGAATTCTAATTCGAGCAGAATTAGGTAATCCAGGATCTTTAATTGGAGATGATCAAATTTA');

-- Viral sequences (collection_id: 2)
INSERT INTO sequences (collection_id, identifier, description, alphabet, sequence) VALUES 
(2, 'SARS_CoV2_spike', 'SARS-CoV-2 spike protein receptor binding domain', 'dna', 'ATGTTCGTTTTCCTGCTGCTGCTGTGGCTGCCAGGCTCCTGCGGCAGCACCAACGGCACCCAGCAGGTGTTCAGCCCTTACACCATTAACAACGGCAACACCGTGCAGGGTGTGAACGGCACCGTGAGCAGCACCAACCTGCCCATCACCCTGACCAAC');

-- Bacterial sequences (collection_id: 3)
INSERT INTO sequences (collection_id, identifier, description, alphabet, sequence) VALUES 
(3, 'E_coli_lacZ', 'E. coli beta-galactosidase gene fragment', 'dna', 'ATGACCATGATTACGCCAAGCGCGCAATTAACCCTCACTAAAGGGAACAAAAGCTGGAGCTCCACCGCGGTGGCGGCCGCTCTAGAACTAGTGGATCCCCCGGGCTGCAGGAATTCGATATCAAGCTTATCGATACCGTCGAC'),
(3, 'B_subtilis_16S', 'Bacillus subtilis 16S ribosomal RNA fragment', 'dna', 'AAGAGTTTGATCCTGGCTCAGGATGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGGACAGACGGGTGAGTAACACGTGGGTAACCTGCCCATAAGACTGGGATAACTCCGGGAAACCGGGGCTAATACCGGATAACATTTTGAACCGC');

-- Plant sequences (collection_id: 4)
INSERT INTO sequences (collection_id, identifier, description, alphabet, sequence) VALUES 
(4, 'Arabidopsis_rbcL', 'Arabidopsis RuBisCO large subunit gene', 'dna', 'ATGTCACCACAAACAGAGACTAAAGCAAGTGTTGGATTCAAAGCTGGTGTTAAAGACGGCAGTACAAGTGTTGGATTCAAAGCTGGTGTTAAAGACTATAAAGATGAAGAACATGTCTATTTCTATGGTGGAGATGTTTGTACTAATATTTGTGATGGTGGACCT');

-- Protein sequences (collection_id: 5)
INSERT INTO sequences (collection_id, identifier, description, alphabet, sequence) VALUES 
(5, 'Insulin_human', 'Human insulin protein sequence', 'protein', 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN'),
(5, 'Hemoglobin_alpha', 'Human hemoglobin alpha chain', 'protein', 'MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR'),
(5, 'Lysozyme_human', 'Human lysozyme antimicrobial protein', 'protein', 'MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANWMCLAKWESGYNTRATNYNAGDRSTDYGIFQINSRYWCNDGKTPGAVNACHLSCSALLQDNIADAVACAKRVVRDPQGIRAWVAWRNRCQNRDVRQYVQGCGV');

-- RNA sequences (collection_id: 6)
INSERT INTO sequences (collection_id, identifier, description, alphabet, sequence) VALUES 
(6, 'ACTB_mRNA', 'Beta-actin mRNA transcript', 'rna', 'AUGGGCCAGAAGGACUGGUGUGAACUGGCACCACACCUUCUACAAUGUGGCUGACGAGGCCCAGAGCAAGAGAGGCAUCCUGACCAUGGGCGACGAGGCCCAGAGCAAGAGAGGCAUCCUGACCAACGGCAGAAGAGGCAUCCUGACCAUGGCGACGAGGCCCAGAGCAAGAGAGGCAUCCUGACCAAC'),
(6, 'INS_mRNA', 'Human insulin mRNA coding sequence', 'rna', 'AUGCCCCGCAAGAAGCGCGGCUUCUUCGGCAAGAAGCGCGGCUUCUUCGGCUACGUCAACAUCAACGAGAAGCUCUACGUCAACAUCAACGAGAAGCUCUACGUCAACAUCAACGAGAAGCUCUACGUCAACAUCAACGAGAAGCUCU');
