-- Human DNA sequences
INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('BRCA1_exon11', 'BRCA1 gene exon 11 fragment - breast cancer susceptibility', 'ATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTAGGTCCGGTTATTGTAACAGACAAGTACCCCAAAGTGGCCAACAACAAGCAGGGATACAAAAATAAG', 'dna');

INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('TP53_exon5', 'TP53 tumor suppressor gene exon 5', 'ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAG', 'dna');

INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('GAPDH_promoter', 'Glyceraldehyde-3-phosphate dehydrogenase promoter region', 'CGCCCAATACGCAAACCGCCTCTCCCCGCGCGTTGGCCGATTCATTAATGCAGCTGGCACGACAGGTTTCCCGACTGGAAAGCGGGCAGTGAGCGCAACGCAATTAATGTGAGTTAGCTCACTCATTAGGCACCCCAGGCTTTACACTTTATGCTTCCGGCTCGTATGTTGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGAAACAGCTATGACCATGATTACGCC', 'dna');

-- mRNA sequences
INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('ACTB_mRNA', 'Beta-actin mRNA transcript', 'AUGGGCCAGAAGGACUGGUGUGAACUGGCACCACACCUUCUACAAUGUGGCUGACGAGGCCCAGAGCAAGAGAGGCAUCCUGACCAUGGGCGACGAGGCCCAGAGCAAGAGAGGCAUCCUGACCAACGGCAGAAGAGGCAUCCUGACCAUGGCGACGAGGCCCAGAGCAAGAGAGGCAUCCUGACCAAC', 'rna');

INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('INS_mRNA', 'Human insulin mRNA coding sequence', 'AUGCCCCGCAAGAAGCGCGGCUUCUUCGGCAAGAAGCGCGGCUUCUUCGGCUACGUCAACAUCAACGAGAAGCUCUACGUCAACAUCAACGAGAAGCUCUACGUCAACAUCAACGAGAAGCUCUACGUCAACAUCAACGAGAAGCUCU', 'rna');

-- Protein sequences
INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('Insulin_human', 'Human insulin protein sequence', 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN', 'protein');

INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('Hemoglobin_alpha', 'Human hemoglobin alpha chain', 'MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR', 'protein');

INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('Lysozyme_human', 'Human lysozyme antimicrobial protein', 'MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANWMCLAKWESGYNTRATNYNAGDRSTDYGIFQINSRYWCNDGKTPGAVNACHLSCSALLQDNIADAVACAKRVVRDPQGIRAWVAWRNRCQNRDVRQYVQGCGV', 'protein');

-- Viral sequences
INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('SARS_CoV2_spike', 'SARS-CoV-2 spike protein receptor binding domain', 'ATGTTCGTTTTCCTGCTGCTGCTGTGGCTGCCAGGCTCCTGCGGCAGCACCAACGGCACCCAGCAGGTGTTCAGCCCTTACACCATTAACAACGGCAACACCGTGCAGGGTGTGAACGGCACCGTGAGCAGCACCAACCTGCCCATCACCCTGACCAAC', 'dna');

-- Bacterial sequences  
INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('E_coli_lacZ', 'E. coli beta-galactosidase gene fragment', 'ATGACCATGATTACGCCAAGCGCGCAATTAACCCTCACTAAAGGGAACAAAAGCTGGAGCTCCACCGCGGTGGCGGCCGCTCTAGAACTAGTGGATCCCCCGGGCTGCAGGAATTCGATATCAAGCTTATCGATACCGTCGAC', 'dna');

INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('B_subtilis_16S', 'Bacillus subtilis 16S ribosomal RNA fragment', 'AAGAGTTTGATCCTGGCTCAGGATGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGGACAGACGGGTGAGTAACACGTGGGTAACCTGCCCATAAGACTGGGATAACTCCGGGAAACCGGGGCTAATACCGGATAACATTTTGAACCGC', 'dna');

-- Plant sequences
INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('Arabidopsis_rbcL', 'Arabidopsis RuBisCO large subunit gene', 'ATGTCACCACAAACAGAGACTAAAGCAAGTGTTGGATTCAAAGCTGGTGTTAAAGACGGCAGTACAAGTGTTGGATTCAAAGCTGGTGTTAAAGACTATAAAGATGAAGAACATGTCTATTTCTATGGTGGAGATGTTTGTACTAATATTTGTGATGGTGGACCT', 'dna');

-- Mitochondrial sequence
INSERT INTO sequences (identifier, description, sequence, alphabet) VALUES 
('Human_mtDNA_COX1', 'Human mitochondrial cytochrome c oxidase I gene fragment', 'ATGTTCGCCGACCGTTGACTATTCTCTACAAACCACAAAGACATTGGAACACTTTATTTTATTTTTGGTATTTGAGCAGGAATAATTGGAACATCACTAAGAATTCTAATTCGAGCAGAATTAGGTAATCCAGGATCTTTAATTGGAGATGATCAAATTTA', 'dna');