/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SequencesIndexImport } from './routes/sequences/index'
import { Route as CollectionsIndexImport } from './routes/collections/index'
import { Route as SequencesSequenceIdImport } from './routes/sequences/$sequenceId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SequencesIndexRoute = SequencesIndexImport.update({
  id: '/sequences/',
  path: '/sequences/',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsIndexRoute = CollectionsIndexImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRoute,
} as any)

const SequencesSequenceIdRoute = SequencesSequenceIdImport.update({
  id: '/sequences/$sequenceId',
  path: '/sequences/$sequenceId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sequences/$sequenceId': {
      id: '/sequences/$sequenceId'
      path: '/sequences/$sequenceId'
      fullPath: '/sequences/$sequenceId'
      preLoaderRoute: typeof SequencesSequenceIdImport
      parentRoute: typeof rootRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/sequences/': {
      id: '/sequences/'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof SequencesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/collections': typeof CollectionsIndexRoute
  '/sequences': typeof SequencesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/collections': typeof CollectionsIndexRoute
  '/sequences': typeof SequencesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/sequences/': typeof SequencesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sequences/$sequenceId' | '/collections' | '/sequences'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sequences/$sequenceId' | '/collections' | '/sequences'
  id:
    | '__root__'
    | '/'
    | '/sequences/$sequenceId'
    | '/collections/'
    | '/sequences/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SequencesSequenceIdRoute: typeof SequencesSequenceIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  SequencesIndexRoute: typeof SequencesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SequencesSequenceIdRoute: SequencesSequenceIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  SequencesIndexRoute: SequencesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sequences/$sequenceId",
        "/collections/",
        "/sequences/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sequences/$sequenceId": {
      "filePath": "sequences/$sequenceId.tsx"
    },
    "/collections/": {
      "filePath": "collections/index.tsx"
    },
    "/sequences/": {
      "filePath": "sequences/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
