/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SequencesIndexRouteImport } from './routes/sequences/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as SequencesSequenceIdRouteImport } from './routes/sequences/$sequenceId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesIndexRoute = SequencesIndexRouteImport.update({
  id: '/sequences/',
  path: '/sequences/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesSequenceIdRoute = SequencesSequenceIdRouteImport.update({
  id: '/sequences/$sequenceId',
  path: '/sequences/$sequenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/collections': typeof CollectionsIndexRoute
  '/sequences': typeof SequencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/collections': typeof CollectionsIndexRoute
  '/sequences': typeof SequencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/sequences/$sequenceId': typeof SequencesSequenceIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/sequences/': typeof SequencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections/$collectionId'
    | '/sequences/$sequenceId'
    | '/collections'
    | '/sequences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections/$collectionId'
    | '/sequences/$sequenceId'
    | '/collections'
    | '/sequences'
  id:
    | '__root__'
    | '/'
    | '/collections/$collectionId'
    | '/sequences/$sequenceId'
    | '/collections/'
    | '/sequences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  SequencesSequenceIdRoute: typeof SequencesSequenceIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  SequencesIndexRoute: typeof SequencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/': {
      id: '/sequences/'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof SequencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences/$sequenceId': {
      id: '/sequences/$sequenceId'
      path: '/sequences/$sequenceId'
      fullPath: '/sequences/$sequenceId'
      preLoaderRoute: typeof SequencesSequenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  SequencesSequenceIdRoute: SequencesSequenceIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  SequencesIndexRoute: SequencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
